name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        run: |
          curl -X POST "https://gitlab.com/api/v4/projects/81841041/trigger/pipeline" \
          --form token=glptt-9a8Cacst6URLX47N9Aa3 \
          --form ref=main
